
server:
  port: 8999

spring:
  application:
    name: springcloud-config

  cloud:
    config:
      server:
        git:
          uri: https://github.com/1811b/sprc-config.git
          search-paths: /config-ck/

        label: master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/