server:
  port:  8097

spring:
  application:
    name: consunmer
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/

ribbon:
  eureka:
    enabled: true

